[package]
name = "utf8strings"
version = "0.1.0"
authors = ["Tim <code@timid.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
